#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "monitorix" domain)

# Remove sources
sudo apt-get remove -y -qq monitorix

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/monitorix.conf

# Reload nginx service
sudo service nginx reload
