#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "monitorix" domain)
path=$(ynh_app_setting_get "monitorix" path)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "monitorix" \
    || ynh_die "Path not available: ${domain}${path}"

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/monitorix.conf"

# Restore Monitorix configuration
sudo cp -a ./monitorix.conf "/etc/monitorix/monitorix.conf"

# Restart webserver
sudo service monitorix restart
sudo service nginx reload
